name: "decision_tree"

params:
  random_state: ${seed}
  class_weight: "balanced"

tuning:
  n_jobs: 5
  cv: 5
  scoring: "roc_auc"
  verbose: 4
  param_grid:
    max_depth: [ 6, 8, 10 ]
    min_samples_leaf: [ 10, 50, 100 ]
    max_features: [ "sqrt", null ]
    criterion: [ "gini", "entropy" ]