name: "xgboost"
n_jobs: 4
cv: 5
scoring: "roc_auc"
verbose: 4
n_estimators: [ 200, 400 ]
max_depth: [ 4, 6, 8 ]
learning_rate: [ 0.05 ]

params:
  subsample: 0.8
  colsample_bytree: 0.8
  reg_lambda: 1.0
  reg_alpha: 0.0
  min_child_weight: 1.0
  gamma: 0.0
  tree_method: "hist"
  eval_metric: "logloss"
  random_state: ${seed}