name: "xgboost"

params:
  tree_method: "hist"
  eval_metric: "logloss"
  random_state: ${seed}

tuning:
  n_jobs: 4
  cv: 5
  scoring: "roc_auc"
  verbose: 4
  param_grid:
    n_estimators: [ 400, 600 ]
    max_depth: [ 6, 8, 10 ]