raw_dir: "data/raw/${year}"
csv_path: "${raw_dir}/${year}_public_lar.csv"
processed_dir: "data/processed/${year}"
dataset_dir: "data/dataset/${year}"
models_root: "artifacts/models"
model_dir: "${models_root}/${model.name}"