features:
  numeric: [
    loan_amount,
    total_units,
    multifamily_affordable_units,
    income,
    debt_to_income_ratio,
  ]

  categorical: [
    preapproval,
    loan_type,
    loan_purpose,
    lien_status,
    reverse_mortgage,
    open_end_line_of_credit,
    business_or_commercial_purpose,
    negative_amortization,
    interest_only_payment,
    balloon_payment,
    other_nonamortizing_features,
    construction_method,
    occupancy_type,
    applicant_credit_score_type,
    co_applicant_credit_score_type,
    derived_loan_product_type,
    derived_dwelling_category,
    manufactured_home_secured_property_type,
    manufactured_home_land_property_interest
  ]

label:
  field: action_taken
  approved: [ 1, 2 ]
  denied: [ 3, 7 ]

allowed_cols: [
  loan_amount, total_units, multifamily_affordable_units,
  income, debt_to_income_ratio, preapproval,
  loan_type, loan_purpose, lien_status, reverse_mortgage,
  open_end_line_of_credit, business_or_commercial_purpose,
  negative_amortization, interest_only_payment, balloon_payment,
  other_nonamortizing_features, construction_method, occupancy_type,
  applicant_credit_score_type, co_applicant_credit_score_type,
  derived_loan_product_type, derived_dwelling_category,
  manufactured_home_secured_property_type,
  manufactured_home_land_property_interest
]

threshold: 0.5