features:
  numeric: [
    loan_amount,
    total_units,
    multifamily_affordable_units,
    income,
    loan_term,
    intro_rate_period,
  ]

  categorical: [
    preapproval,
    loan_type,
    loan_purpose,
    lien_status,
    reverse_mortgage,
    open_end_line_of_credit,
    business_or_commercial_purpose,
    negative_amortization,
    interest_only_payment,
    balloon_payment,
    other_nonamortizing_features,
    construction_method,
    occupancy_type,
    manufactured_home_secured_property_type,
    manufactured_home_land_property_interest
  ]

label:
  field: action_taken
  approved: [ 1, 2 ]
  denied: [ 3, 7 ]

allowed_cols: [
  # Core loan details
  loan_amount,
  loan_term,
  intro_rate_period,

  # Loan category
  loan_type,
  loan_purpose,
  lien_status,
  reverse_mortgage,
  open_end_line_of_credit,
  business_or_commercial_purpose,

  # Applicant
  income,
  preapproval,

  # Property
  total_units,
  multifamily_affordable_units,
  construction_method,
  occupancy_type,

  # Manufactured home details
  manufactured_home_secured_property_type,
  manufactured_home_land_property_interest,

  # Product features
  negative_amortization,
  interest_only_payment,
  balloon_payment,
  other_nonamortizing_features,
]

threshold: 0.5